### ISSUE TITLE
Error on missing container not useful

### ISSUE THREAD

**Issue by phxnsharp** [direktiv/direktiv#753]
**Describe the bug**
When a container is not found, the error received does not help you solve the issue.

**To Reproduce**

 - `docker run --privileged -p 8080:80 -ti direktiv/direktiv-kube`
 - Connect to the UI on http://localhost:8080
 - Run the examples/greeting/greeting example
 - You will receive the following error:
 
```
[10:05:41.877] Preparing workflow triggered by api.
[10:05:41.901] Running state logic (step:1) -- validate-input
[10:05:41.908] Transitioning to next state: greeter (2).
[10:05:41.915] Running state logic (step:2) -- greeter
[10:05:41.916] Sleeping until child '50690a1a-52a6-42e7-b5ea-e6b285900d3e' returns (greeter).
[10:08:51.853] Child '50690a1a-52a6-42e7-b5ea-e6b285900d3e' returned.
[10:08:51.860] Action crashed due to an internal error: Post "http://workflow-13087262918469761732-greeter.direktiv-services-direktiv": dial tcp: lookup workflow-13087262918469761732-greeter.direktiv-services-direktiv on 10.43.0.10:53: no such host
[10:08:51.882] Instance failed with uncatchable error: Post "http://workflow-13087262918469761732-greeter.direktiv-services-direktiv": dial tcp: lookup workflow-13087262918469761732-greeter.direktiv-services-direktiv on 10.43.0.10:53: no such host (github.com/direktiv/direktiv/pkg/flow/states.(*actionLogic).processActionResults /src/pkg/flow/states/action.go:235)
```

**Expected behavior**
As delivered, the workflow uses the image `direktiv/greeting:v4`, which does not exist on GitHub. Only v3 and earlier exist. I would expect that somewhere in the logs it would tell me this fact.

Perhaps the error is going somewhere else, but it is not in the docker terminal, nor anywhere I can find in the web UI. 

Note that if v4 is ever created, or if the example workflow text is fixed, this will no longer be a valid reproduction recipe. However, that is not the issue I'm concerned about. Making failed workflow runs debuggable/fixable is very important.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS
 - Browser: Firefox 109.0.1
 - Version: v0.7.0-9d5828f-dirty

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by jensg-st** [comment]
Hi,

I totally agree and we discussed that in the past. I'm wondering if that should be in the logs or arther a status section on the instance. For UI use a status page would be better but I'm suing the CLI mostly so it has to go into the logs. We just need to find the best way to get it into the logs because this would not be coming from the container or flow but has to be an additional request to get the Knative service information. 

We are doing this request already and it is available in the UI but it is not obvious. If you go to the "Overview section:

![imag1](https://user-images.githubusercontent.com/10879611/218389850-b2b8d3eb-6e75-4717-84b9-4343c9b1b2ad.png)

There you can find a list of actual and past containers used in that workflow. 

![image2](https://user-images.githubusercontent.com/10879611/218390012-0f5e12da-80b3-4881-a1b5-e81b42cd9c7a.png)

If there is an error you can expand the "Show Details" links at the end and it would show you what is wrong. Again, we just need to find a good way to get this into the logs. I have marked this issue as an improvement and let it open. 

![image3](https://user-images.githubusercontent.com/10879611/218390251-16592766-f7be-4f5b-9994-e7df95e887e9.png)

**Comment by marcellodesales** [comment]
# panic: exit status 1 while docker run

```console
$ docker run --privileged -p 8080:80 -ti dockerhub.docker.artifactory.viasat.com/direktiv/direktiv-kube
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2023/04/10 05:28:16 all-in-one version of direktiv
2023/04/10 05:28:16 waiting for k3s kubeconfig
2023/04/10 05:28:16 starting k3s now
2023/04/10 05:28:16 evacuate cgroup2
2023/04/10 05:28:28 waiting for kubernetes API
2023/04/10 05:28:40 waiting for systems pods
2023/04/10 05:29:34 k3s up
2023/04/10 05:29:34 running knative helm
2023/04/10 05:29:34 adding proxy settings to file: /tmp/knative.yaml
2023/04/10 05:29:34 http proxy not set
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
W0410 05:29:54.727137     243 warnings.go:70] autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler
W0410 05:29:54.751095     243 warnings.go:70] autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler
W0410 05:29:59.879496     243 warnings.go:70] autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler
W0410 05:29:59.882523     243 warnings.go:70] autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler
NAME: knative
LAST DEPLOYED: Mon Apr 10 05:29:41 2023
NAMESPACE: knative-serving
STATUS: deployed
REVISION: 1
TEST SUITE: None
2023/04/10 05:30:03 running on GCP: false
2023/04/10 05:30:03 installing docker repository
2023/04/10 05:30:03 applying registry.yaml
namespace/registry-ns created
serviceaccount/registry-sa created
pod/docker-registry-pod created
service/docker-registry created
2023/04/10 05:30:19 deploying db
deployment.apps/postgres created
persistentvolume/postgres-pv-volume created
persistentvolumeclaim/postgres-pv-claim created
service/postgres created
deploying direktiv
2023/04/10 05:30:30 adding apikey if configured
2023/04/10 05:30:30 adding proxy settings to file: /debug.yaml
2023/04/10 05:30:30 http proxy not set
2023/04/10 05:30:30 creating service namespace
namespace/direktiv-services-direktiv created
2023/04/10 05:30:33 running direktiv helm
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
panic: exit status 1

goroutine 19 [running]:
main.main.func1()
	/app/main.go:87 +0x45
created by main.main
	/app/main.go:84 +0x71
```

**Comment by jensg-st** [comment]
We are building a multi-arch image this week. I will update this issue when it's done.
